pipeline:
  name: nodejshelloworld
  identifier: nodejshelloworld
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: nodejshelloworld
        build: <+input>
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: DhrubaDemoCI2
              namespace: dhruba-demo-ci
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: install node modules
                  identifier: install_node_modules
                  spec:
                    connectorRef: account.harnessImage
                    image: node:14
                    shell: Sh
                    command: |
                      npm install
              - step:
                  type: Run
                  name: create image
                  identifier: create_image
                  spec:
                    connectorRef: account.harnessImage
                    image: node:14
                    shell: Sh
                    command: |-
                      FROM node:14
                      WORKDIR /usr/src/app
                      COPY package*.json index.js ./
                      RUN npm install
                      EXPOSE 3000
                      CMD ["node", "index.js"]
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push an image to docker
                  identifier: build_and_push_an_image_to_docker
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - latest
